### ISSUE TITLE
Navbar message alert counter

### ISSUE THREAD

**Issue by EvanColon** [neg-0/dod-fitness#10]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/27d8826e-a9ad-4d39-9673-f41b622f7303">

The navbar says a new user has 3 new messages based on the counter even if a user has no messages in their inbox. 

This can be remedied by saving messages to the db with a column for a boolean of "read/unread" messages. Then having the counter update as the db is polled periodically rows that include "unread".

**Comment by neg-0** [comment]
removed message bell until we implement new messaging system
