### ISSUE TITLE
/workout-plan endpoint after ai generates workout plan

### ISSUE THREAD

**Issue by EvanColon** [neg-0/dod-fitness#9]
<img width="417" alt="image" src="https://github.com/user-attachments/assets/efc7860b-45aa-4291-90a0-8198db1f631c">

The workout plan generator sets the user's goal to something unrelated to user's profile specified goals or goals specified in the workout plan wizard. This can be fixed by requiring the goal to be determined in the user's profile and if another goal is specified in the workout wizard overwrite the goal stated in the user's profile with the new goal to allow for customization on the fly without having to update the user profile.

**Comment by neg-0** [comment]
fixed by adding the LLM generated goal (pulls from profile and user input)
